name: transformers-seminar-workshop
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pandas
  - numpy
  - jupyter
  - ipykernel
  - pytorch
  - pytorch-cuda=11.7
  - pip
  - pip:
      - black
      - matplotlib==3.7.1
      - seaborn==0.10.0
