name: transformers-seminar-workshop
channels:
  - defaults
  - conda-forge
  - huggingface 
dependencies:
  - python=3.9
  - pandas
  - numpy
  - nltk
  - jupyter
  - ipykernel
  - transformers
  - pip
  - pip:
      - black
      - matplotlib
      - seaborn
