name: Create Google Colab notebooks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup for colab
        run: make setup-for-colab
      - name: Commit and push changes
        run: |
          git config user.name "Petteri U. Ranta"
          git config user.email "petteri.u.ranta@gmail.com"
          git checkout -b google-colab
          git commit -am "Clear code cells and add Colab setup headers"
          git push --set-upstream origin google-colab
